# Generated by Django 5.1.3 on 2024-11-25 01:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueque', '0003_customusers_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
