# Generated by Django 5.1.3 on 2024-11-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueque', '0005_comic_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comics/'),
        ),
    ]
