# Generated by Django 5.1.3 on 2024-11-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueque', '0006_alter_comic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offered_item_image',
            field=models.ImageField(blank=True, null=True, upload_to='offers/'),
        ),
    ]
