# Generated by Django 5.1.3 on 2024-11-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueque', '0007_offer_offered_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='status',
            field=models.CharField(choices=[('Sin Ofertas Activas', 'Sin Ofertas Activas'), ('Trueque en Progreso', 'Trueque en Progreso'), ('Con Ofertas Activas', 'Con Ofertas Activas'), ('Trueque Finalizado', 'Trueque Finalizado')], default='Sin Ofertas Activas', max_length=20),
        ),
    ]
